# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
import numpy as np

#### 2. Print your NumPy version.

In [3]:
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [28]:
# Method 1
a=np.random.random((2,3,5))

In [15]:
import random
my_randoms=[]
for i in range (30):
    my_randoms.append(random.randrange(1, 101, 1))
a1=np.reshape(my_randoms,(2,3,5))

# Method 2
a = np.arange(30).reshape(2,3,5)

In [14]:
from numpy import random
a = random.rand(2, 3, 5)

#### 4. Print *a*.


In [29]:
print(a)

[[[0.56295544 0.75833379 0.83135614 0.31686792 0.15974801]
  [0.50737468 0.09490094 0.8947016  0.81616859 0.65499808]
  [0.28020563 0.39880587 0.23819397 0.08053343 0.03546555]]

 [[0.99769535 0.82134684 0.89555472 0.0669393  0.75298723]
  [0.19768421 0.55399974 0.99316218 0.810064   0.70550706]
  [0.03219979 0.93012363 0.50305194 0.47984446 0.5732228 ]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [23]:
b=np.full(((5,3,2)),1)
##b=np.ones(5,3,2)


#### 6. Print *b*.


In [24]:
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [25]:
print('size of a: ',a.shape)
print('size of b: ',b.shape)
if a.shape==b.shape:
    print(' a and b have the same size')
else:
    print('a and b dont have the same size')

size of a:  (2, 3, 5)
size of b:  (5, 3, 2)
a and b dont have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [20]:
print(a+b)
## We aren't able to add a and b. Because a and b don't have the same size

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [30]:
c=np.transpose(b)
print(c)
c.shape

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [31]:
d=a+c
print(d)

[[[1.56295544 1.75833379 1.83135614 1.31686792 1.15974801]
  [1.50737468 1.09490094 1.8947016  1.81616859 1.65499808]
  [1.28020563 1.39880587 1.23819397 1.08053343 1.03546555]]

 [[1.99769535 1.82134684 1.89555472 1.0669393  1.75298723]
  [1.19768421 1.55399974 1.99316218 1.810064   1.70550706]
  [1.03219979 1.93012363 1.50305194 1.47984446 1.5732228 ]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [32]:
print(a)

print("--------------------------")
print(d)

[[[0.56295544 0.75833379 0.83135614 0.31686792 0.15974801]
  [0.50737468 0.09490094 0.8947016  0.81616859 0.65499808]
  [0.28020563 0.39880587 0.23819397 0.08053343 0.03546555]]

 [[0.99769535 0.82134684 0.89555472 0.0669393  0.75298723]
  [0.19768421 0.55399974 0.99316218 0.810064   0.70550706]
  [0.03219979 0.93012363 0.50305194 0.47984446 0.5732228 ]]]
--------------------------
[[[1.56295544 1.75833379 1.83135614 1.31686792 1.15974801]
  [1.50737468 1.09490094 1.8947016  1.81616859 1.65499808]
  [1.28020563 1.39880587 1.23819397 1.08053343 1.03546555]]

 [[1.99769535 1.82134684 1.89555472 1.0669393  1.75298723]
  [1.19768421 1.55399974 1.99316218 1.810064   1.70550706]
  [1.03219979 1.93012363 1.50305194 1.47984446 1.5732228 ]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [34]:
e=a*c

#### 13. Does *e* equal to *a*? Why or why not?


In [35]:
if e.all()==a.all():
    print('e is equal to a')
else:
    print('e is not equal to a')
print(a.shape)
print(e.shape)
## because c contains only 1 inside

e is equal to a
(2, 3, 5)
(2, 3, 5)


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [46]:
d_max=np.max(d)
print('d_max: ',d_max)

d_min=np.min(d)
print('d_min: ',d_min )

d_mean=np.mean(d)
print('d_mean: ',d_mean)


d_max:  1.9976953492057268
d_min:  1.0321997898767408
d_mean:  1.5314664303962253


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [47]:
f=np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [58]:
ar= []
for i in np.nditer(d):
    if i>d.min() and i<d.mean():
        ar.append(25)
    elif i>d.mean() and i<d.max():
        ar.append(75)
    elif i==d.mean():
        ar.append(50)
    elif i<d.min():
        ar.append(0)   
    else :
        ar.append(100)
f=np.reshape(ar,a.shape)

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [59]:
print(d)
print('----------------------------------------')
print(f)

[[[1.56295544 1.75833379 1.83135614 1.31686792 1.15974801]
  [1.50737468 1.09490094 1.8947016  1.81616859 1.65499808]
  [1.28020563 1.39880587 1.23819397 1.08053343 1.03546555]]

 [[1.99769535 1.82134684 1.89555472 1.0669393  1.75298723]
  [1.19768421 1.55399974 1.99316218 1.810064   1.70550706]
  [1.03219979 1.93012363 1.50305194 1.47984446 1.5732228 ]]]
----------------------------------------
[[[ 75  75  75  25  25]
  [ 25  25  75  75  75]
  [ 25  25  25  25  25]]

 [[100  75  75  25  75]
  [ 25  75  75  75  75]
  [100  75  25  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [61]:
ar= []
for i in np.nditer(d):
    if i>d.min() and i<d.mean():
        ar.append('B')
    elif i>d.mean() and i<d.max():
        ar.append('D')
    elif i==d.mean():
        ar.append('C')
    elif i<d.min():
        ar.append('A')   
    else :
        ar.append('E')
f=np.reshape(ar,a.shape)
f

array([[['D', 'D', 'D', 'B', 'B'],
        ['B', 'B', 'D', 'D', 'D'],
        ['B', 'B', 'B', 'B', 'B']],

       [['E', 'D', 'D', 'B', 'D'],
        ['B', 'D', 'D', 'D', 'D'],
        ['E', 'D', 'B', 'B', 'D']]], dtype='<U1')